### ISSUE TITLE
Broken in Python 3.4 (rasbian latest)

### ISSUE THREAD

**Issue by ryanhunt** [arkilis/telstra-sms-sdk#1]
HI there. 

I've got the lastest Rasbian (Debian for Raspberry Pi) build which includes `Python 3.4.2`. The packages I have install via `pip3` are:

- `requests-2.13.0`
- `telstra-sms-sdk-0.0.7`

When using the sample code I get this error:

`Traceback (most recent call last):
  File "./sendsms.py", line 3, in <module>
    from telstra_sms_sdk.sms import TelstraSMS
  File "/usr/local/lib/python3.4/dist-packages/telstra_sms_sdk/sms.py", line 56
    print str(e)
            ^
SyntaxError: invalid syntax`

**Comment by ryanhunt** [comment]
Ok I figured out how to fix it. 

Two changes required:

1. Change all references of `print str(e)` to `print(str(e))`
1. Change all references of `json.loads(r.content)` to `json.loads(r.text)`

**Comment by ryanhunt** [comment]
Ok, I created a fork - fixed the bugs and extended it to support checking the status of sent messages, receiving replies and also checking user quota. I'd advise you review my code and merge with yours.

https://github.com/ryanhunt/telstra-sms-sdk
